### ISSUE TITLE
feat: add parameter for index/follow configuration

### ISSUE THREAD

**Issue by davidsneighbour** [davidsneighbour/hugo-robots#53]
Add frontmatter parameters to configure meta-robots configuration for index and follow setup. Best put it under some form of `theme` or `config` parent tag. See also davidsneighbour/hugo-sitemap#48

**Comment by davidsneighbour** [comment]
Add frontmatter to individual pages with the following setup:

```yaml
config:
  follow: true
  index: false
```

- follow (bool): set follow/nofollow
- index (bool): set index/noindex

Add/edit global defaults in config.toml or config/_defaults/paramts.toml:

```toml
[dnb.robots.defaults]
index = true
follow = true
```

Defaults without any configuration is true in both parameters.

If the parameters are string they will be sanitized and evaluated as boolean. Not sure if Golang is too happy with that and what the results will be, so it's probably best to just go with true/false without any quotes.
